In [1]:
import numpy as np
vector1 = np.zeros(10)
vector1[4] = 1
print("Program 1 Output:", vector1)

Program 1 Output: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
a = int(input("Enter number of rows (a): "))
b = int(input("Enter number of columns (b): "))
array2 = np.random.rand(a, b)
print("Program 2 Output:\n", array2)
print("Average:", np.mean(array2))


Program 2 Output:
 [[0.32249252 0.4919275  0.94481986 0.56097964 0.43845507 0.18835796
  0.64269054 0.45916604 0.08565976 0.5052063  0.2942665  0.28245431]
 [0.33835479 0.32663159 0.1836692  0.57627932 0.31105889 0.06892214
  0.93729264 0.73233262 0.87331826 0.23730742 0.7953466  0.28860173]
 [0.50017249 0.66979995 0.28542885 0.13761912 0.93358289 0.22360744
  0.46486938 0.53525253 0.14424089 0.62570504 0.91371535 0.39107902]
 [0.65958952 0.65654031 0.30235988 0.27552051 0.96195767 0.87125954
  0.07166583 0.83483905 0.04870149 0.98816043 0.66968652 0.47088636]
 [0.4691216  0.27421229 0.17952853 0.45634253 0.90299955 0.13872902
  0.32566028 0.06219453 0.77229451 0.07064252 0.95050478 0.50916991]
 [0.68229541 0.01688069 0.69812684 0.83991647 0.66214609 0.90368101
  0.80674551 0.61349728 0.63136596 0.54868854 0.73025346 0.82940474]
 [0.79915356 0.85074133 0.58228846 0.94191626 0.13973834 0.33357025
  0.56205101 0.32573698 0.7746901  0.89596413 0.0084664  0.58944355]
 [0.2128015  0.5218487

In [3]:
vector3 = np.linspace(0, 1, 12)[1:-1]
print("Program 3 Output:", vector3)


Program 3 Output: [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [4]:
try:
    identity_matrix = np.eye(3, 4)
    print("Program 4 Output:\n", identity_matrix)
except Exception as e:
    print("Program 4 Error:", e)


Program 4 Output:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [5]:
matrix5 = np.tile(np.arange(5), (5, 1))
print("Program 5 Output:\n", matrix5)


Program 5 Output:
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [6]:
user_input = list(map(int, input("Enter at least 10 numbers separated by space: ").split()))
user_input.sort()
print("Sorted list:", user_input)
print("Elements from index 2 to 5:", user_input[2:6])
print("Elements from index 5 to 8:", user_input[5:9])
print("Elements from index 2 to 9:", user_input[2:10])

Sorted list: [1]
Elements from index 2 to 5: []
Elements from index 5 to 8: []
Elements from index 2 to 9: []


In [7]:
rand_array = np.random.randint(1, 100, size=10)
print("Original Random Array:", rand_array)
sorted_array = np.sort(rand_array)
print("Sorted Array:", sorted_array)
reshaped_array = sorted_array.reshape(2, 5)  # Assumes 10 elements
print("Reshaped Array:\n", reshaped_array)

Original Random Array: [68 23 31 86 22 14 76 97 27 98]
Sorted Array: [14 22 23 27 31 68 76 86 97 98]
Reshaped Array:
 [[14 22 23 27 31]
 [68 76 86 97 98]]


In [8]:
import pandas as pd
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([1, 2, 3])
print("Addition:\n", s1 + s2)
print("Subtraction:\n", s1 - s2)
print("Multiplication:\n", s1 * s2)
print("Division:\n", s1 / s2)

Addition:
 0    11
1    22
2    33
dtype: int64
Subtraction:
 0     9
1    18
2    27
dtype: int64
Multiplication:
 0    10
1    40
2    90
dtype: int64
Division:
 0    10.0
1    10.0
2    10.0
dtype: float64


In [10]:
data = {
    'EmployeeID': [101, 102, 103, 104, 105],
    'Name': ['John Smith', 'Alice Brown', 'Bob White', 'Emma Green', 'Charlie Red'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Age': [30, 28, 35, 40, 25],
    'Salary': [70000, 60000, 80000, 90000, 55000],
    'JoinDate': pd.to_datetime(['2018-07-15', '2020-03-10', '2016-11-01', '2012-05-25', '2021-06-01']),
    'ExperienceYears': [5, 3, 7, 11, 2]
}
df = pd.DataFrame(data)


In [11]:
# 1. Select Name and Salary
print("\nNames and Salaries:\n", df[['Name', 'Salary']])


Names and Salaries:
           Name  Salary
0   John Smith   70000
1  Alice Brown   60000
2    Bob White   80000
3   Emma Green   90000
4  Charlie Red   55000


In [12]:
# 2. Employees in IT
print("\nIT Department:\n", df[df['Department'] == 'IT'])


IT Department:
    EmployeeID        Name Department  Age  Salary   JoinDate  ExperienceYears
0         101  John Smith         IT   30   70000 2018-07-15                5
2         103   Bob White         IT   35   80000 2016-11-01                7


In [13]:
# 3. Employees older than 30, avg salary per dept
print("\nEmployees older than 30:\n", df[df['Age'] > 30])
print("\nAverage Salary per Department:\n", df.groupby('Department')['Salary'].mean())



Employees older than 30:
    EmployeeID        Name Department  Age  Salary   JoinDate  ExperienceYears
2         103   Bob White         IT   35   80000 2016-11-01                7
3         104  Emma Green    Finance   40   90000 2012-05-25               11

Average Salary per Department:
 Department
Finance    90000.0
HR         57500.0
IT         75000.0
Name: Salary, dtype: float64


In [14]:
# 4. Count employees per department
print("\nCount per Department:\n", df['Department'].value_counts())


Count per Department:
 Department
IT         2
HR         2
Finance    1
Name: count, dtype: int64


In [15]:
# 5. Add Bonus column
df['Bonus'] = df['Salary'] * 0.10
print("\nWith Bonus:\n", df[['Name', 'Salary', 'Bonus']])


With Bonus:
           Name  Salary   Bonus
0   John Smith   70000  7000.0
1  Alice Brown   60000  6000.0
2    Bob White   80000  8000.0
3   Emma Green   90000  9000.0
4  Charlie Red   55000  5500.0


In [16]:
# 6. Replace HR with Human Resources
df['Department'] = df['Department'].replace('HR', 'Human Resources')
print("\nUpdated Departments:\n", df['Department'])


Updated Departments:
 0                 IT
1    Human Resources
2                 IT
3            Finance
4    Human Resources
Name: Department, dtype: object


In [ ]:
# 7. Longest tenure
min_date = df['JoinDate'].min()
print("\nLongest Tenure Employee:\n", df[df['JoinDate'] == min_date])




Longest Tenure Employee:
    EmployeeID        Name Department  Age  Salary   JoinDate  ExperienceYears  \
3         104  Emma Green    Finance   40   90000 2012-05-25               11   

    Bonus  
3  9000.0  


In [18]:
# 8. SalaryCategory column
df['SalaryCategory'] = df['Salary'].apply(lambda x: 'High' if x > 75000 else 'Low')
print("\nSalary Category:\n", df[['Name', 'SalaryCategory']])


Salary Category:
           Name SalaryCategory
0   John Smith            Low
1  Alice Brown            Low
2    Bob White           High
3   Emma Green           High
4  Charlie Red            Low


In [20]:
# 9. Check duplicates
df = df.drop_duplicates(subset='EmployeeID')

In [21]:
# 10. Median Age
print("\nMedian Age:", df['Age'].median())



Median Age: 30.0
